### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by RobSenix** [appsthatmatter/GraphView#456]
I am using **appendData()** to create a realtime graph.  I call this method during a Bluetooth notification callback which is not running on the main UI thread.  This creates a ConcurrentModificationException because the LineGraphSeries is being accessed by my thread to add a new DataPoint, and also an iterator in the onDraw routine of the GraphView.  I've been able to work around the problem by pushing my call to appendData() onto the UI thread, but a better solution would be to protect the LineGraphSeries storing the DataPoints inside GraphView using synchronization.  This would allow any thread to add data to the graph without pushing the work onto the UI thread.  Something like this might work:

**List list = Collections.synchronizedList(new ArrayList(...));**

**Comment by mitchtabian** [comment]
I'm also getting this error.

It's very strange. I can just move my appendData() calls to different places in my code and it works.

Very hard to find a pattern though and adding addition series is a pain.

**Comment by mitchtabian** [comment]
Hmm... I changed the order I was appending data and it worked... 

For example:
I have 3 series, let's call them series1, series2 and series3.
They are PointsGraphSeries<DataPoint> type.

It was crashing when I added them like any of the ways below:

    graph.appendData(series2, series3, series1);
    graph.appendData(series3, series2, series1);
    graph.appendData(series1, series3, series2);
    graph.appendData(series3, series1, series1);

But it worked when I added them like this:

    graph.appendData(series1, series2, series3);

I cannot explain this. The only pattern I see is that I added them to the graph in the order that I populated the series in my code.
For example as my code executes it populate series then series2 and finally series3.

I don't understand. Pretty weird. But it works so I'm happy :).

**Comment by vadimmelnicuk** [comment]
Any updates on this matter? I am experiencing same issue.

**Comment by vadimmelnicuk** [comment]
The error code is:

```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at com.jjoe64.graphview.series.BaseSeries$1.next(BaseSeries.java:236)
    at com.jjoe64.graphview.series.BaseSeries$1.next(BaseSeries.java:186)
    at com.jjoe64.graphview.series.LineGraphSeries.draw(LineGraphSeries.java:255)
    at com.jjoe64.graphview.GraphView.drawGraphElements(GraphView.java:301)
    at com.jjoe64.graphview.GraphView.onDraw(GraphView.java:323)
    at android.view.View.draw(View.java:18313)
    at android.view.View.updateDisplayListIfDirty(View.java:17291)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
    at android.view.View.updateDisplayListIfDirty(View.java:17254)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3093)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2889)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2483)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1490)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7027)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
    at android.view.Choreographer.doCallbacks(Choreographer.java:702)
    at android.view.Choreographer.doFrame(Choreographer.java:638)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6692)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by RobSenix** [comment]
@vadimmelnicuk 
The simplest way to handle this is to manipulate all the data manipulation in the main thread.  I do this by posting messages from background threads and this seems to have solved the problem.

**Comment by vadimmelnicuk** [comment]
@RobSenix Thank you for a prompt response. I tried moving my appendData function into UI Thread. However, this produces abrupt graph with some visible insertion skips. Could you please share an example that works for you?

**Comment by RobSenix** [comment]
@vadimmelnicuk 
Nothing very special here, I'm an Android beginner, but this worked enough for me:

    public void addMeasurement(MeasurementFragment.MeasurementInfo measurementInfo)
    {
        final LineGraphSeries<DataPoint> series = mSeriesList.get(measurementInfo.address -1);

        // Data from a new channel arrived, setup a new series
        if (series.isEmpty())
        {
            int colors[] = {Color.BLUE,Color.GREEN,Color.RED,Color.YELLOW,Color.CYAN,Color.MAGENTA};
            if (mMilliOffset == 0) mMilliOffset = measurementInfo.lastUpdateMillis;
            series.setTitle("Sensor " + measurementInfo.address);
            series.setColor(colors[mGraph.getSeries().size() % colors.length]);
            mGraph.addSeries(series);
            mGraph.getLegendRenderer().setVisible(true);
            mGraph.getLegendRenderer().setFixedPosition(20,20);

        }

        Double secs = (measurementInfo.lastUpdateMillis - mMilliOffset)/1000.0;

        final DataPoint dataPoint = new DataPoint(secs, measurementInfo.measurement);

        // Add data to existing series
        mActivity.runOnUiThread(new Runnable()
        {
            @Override
            public void run()
            {
                series.appendData(dataPoint,true,1000);
            }
        });
    }


This plots data from sensors, and as new sensors arrive a new series is created and added to the chart.  Hope this helps.

**Comment by vadimmelnicuk** [comment]
@RobSenix Again, thanks for the support. I think, I managed to sort this out. I followed your advice on running appendData function in UI Thread. However, I also discovered that lagging data appearance happened due to type of variable I used while creating a DataPoint. It seems like lagging behaviour can be avoid if static variable used rather than final one, defined right before runOnUiThread function. I have pasted my working solution.

```
runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                    FragmentPolarH7.rrGraphSeries.appendData(new DataPoint(mCounter, cleanRR), true, FragmentPolarH7.graphWidth);
                                }
                            });
```

**Comment by appsthatmatter** [comment]
closed, because too old. If the problem still exists, please reopen a new ticket.

**Comment by JosePedroNobre** [comment]
@jjoe64 I have got the same problem. I am trying to appendData in some x,y value and it works. But when I try to do another action like resetData our append another Data the lib gives me an "java.util.ConcurrentModificationException".


This is my code

```
class MainActivity : AppCompatActivity() {


    lateinit var series:LineGraphSeries<DataPoint>

    private lateinit var xySeries: PointsGraphSeries<DataPoint>


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val series = LineGraphSeries(
            arrayOf(
                DataPoint(9.0, 9.0),
                DataPoint(10.0, 10.0),
                DataPoint(11.0, 11.0),
                DataPoint(12.0, 12.0),
                DataPoint(13.0, 13.0),
                DataPoint(14.0, 14.0)))
        graph.addSeries(series)

        var staticLabelsFormatter = StaticLabelsFormatter(graph)
        staticLabelsFormatter.setHorizontalLabels(arrayOf<String>("2018", "2019", "2020","2021","2022","2023"))
        graph.viewport.isScrollable = true
        graph.gridLabelRenderer.gridStyle = GridLabelRenderer.GridStyle.NONE
        graph.gridLabelRenderer.isVerticalLabelsVisible = false
        graph.gridLabelRenderer.labelFormatter = staticLabelsFormatter


        series.color = Color.BLACK
        series.thickness = 6
        series.isDrawBackground = true
        series.isDrawDataPoints = true
        series.isDrawDataPoints = false
        series.backgroundColor = Color.parseColor("#0D000000")
        xySeries = PointsGraphSeries()



        series.setOnDataPointTapListener { s, dataPoint ->


            xySeries.appendData(DataPoint(dataPoint.x, dataPoint.y), true, 1000)
            //xySeries.resetData(arrayOf(DataPoint(0.0, 0.0)))
            createScatterPlot()
            Toast.makeText(
                applicationContext,
                "Series1: On Data Point clicked: $dataPoint",
                Toast.LENGTH_SHORT
            ).show()
        }

    }

    private fun createScatterPlot(){
        xySeries.shape = PointsGraphSeries.Shape.RECTANGLE
        xySeries.color = Color.BLUE
        xySeries.size = 20f
        graph.addSeries(xySeries)
    }
}
```

**Comment by eakteam** [comment]
This fix introduce new crash :

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 3936 free bytes and 3KB until OOM
       at java.util.concurrent.CopyOnWriteArrayList.iterator + 188(CopyOnWriteArrayList.java:188)
       at com.jjoe64.graphview.Viewport.calcCompleteRange + 759(Viewport.java:759)
       at com.jjoe64.graphview.GraphView.onDataChanged + 283(GraphView.java:283)
       at com.jjoe64.graphview.series.BaseSeries.drawSelection(BaseSeries.java:58)
       at com.jjoe64.graphview.Viewport.scrollToEnd + 1180(Viewport.java:1180)
       at com.jjoe64.graphview.series.BaseSeries.appendData + 478(BaseSeries.java:478)
       at com.jjoe64.graphview.series.LineGraphSeries.appendData + 670(LineGraphSeries.java:670)
       at com.jjoe64.graphview.series.BaseSeries.appendData + 496(BaseSeries.java:496)
```

**Comment by MadhavShroff** [comment]
Had the same error when appending to LineSeries from doInBackground() of an AsyncTask, which runs every 100ms.

**Comment by shivanshPurple** [comment]
@RobSenix solution worked for me, Don't use a separate thread for appending the data. Just run it on the ui thread by calling 
runOnUiThread().
