### ISSUE TITLE
GraphView Crash

### ISSUE THREAD

**Issue by Pythogen7** [appsthatmatter/GraphView#520]
I have a graph view in my application, except several users are reporting this crash:

java.lang.IllegalArgumentException: 
  at java.util.HashMap.<init>(HashMap.java:203)
  at java.util.HashMap.<init>(HashMap.java:232)
  at java.util.LinkedHashMap.<init>(LinkedHashMap.java:208)
  at com.jjoe64.graphview.GridLabelRenderer.adjustHorizontal(GridLabelRenderer.java:901)
  at com.jjoe64.graphview.GridLabelRenderer.adjustSteps(GridLabelRenderer.java:934)
  at com.jjoe64.graphview.GridLabelRenderer.draw(GridLabelRenderer.java:1067)
  at com.jjoe64.graphview.GraphView.drawGraphElements(GraphView.java:299)
  at com.jjoe64.graphview.GridLabelRenderer.draw(GridLabelRenderer.java:1062)
  at com.jjoe64.graphview.GraphView.drawGraphElements(GraphView.java:299)
  at com.jjoe64.graphview.GraphView.onDraw(GraphView.java:323)
  at android.view.View.draw(View.java:18324)
  at android.view.View.updateDisplayListIfDirty(View.java:17302)
  at android.view.View.draw(View.java:18086)

I investigated the code and it seems that a HashMap is being initialized to a value less than zero. The value for numHorizontalLabels is being used on GridLabelRenderer.java:901 to initialize the HashMap. So I am assuming it became negative somehow. 

Here is all the code in my java classes that I am using regarding the GridLabelRenderer:

GridLabelRenderer glr = myGraphView.getGridLabelRenderer();
glr.setPadding(0);
glr.setHorizontalLabelsVisible(false);
glr.setGridColor(ContextCompat.getColor(context, R.color.myColor));

Unfortunately, I cannot wrap it all in a try catch statement because the crash happens when onDraw() is called.

**Comment by jordantrain** [comment]
I'm also seeing this.

**Comment by appsthatmatter** [comment]
i prevent it to initialise with invalid number, but I'm not sure if it will crash otherwise now. because it seems that the calculation somehow is wrong - maybe because of the viewport height...
