### ISSUE TITLE
App crashes when i zooming

### ISSUE THREAD

**Issue by NickTxD** [appsthatmatter/GraphView#538]
App crashes when i zooming often or trying draw a lot of points.

Stack trace:
FATAL EXCEPTION: main
                                                                   Process: nicktxd.graphtest, PID: 13650
                                                                   Theme: themes:{}
                                                                   java.util.ConcurrentModificationException
                                                                       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                       at com.jjoe64.graphview.series.BaseSeries$1.next(BaseSeries.java:236)
                                                                       at com.jjoe64.graphview.series.BaseSeries$1.next(BaseSeries.java:186)
                                                                       at com.jjoe64.graphview.series.LineGraphSeries.draw(LineGraphSeries.java:255)
                                                                       at com.jjoe64.graphview.GraphView.drawGraphElements(GraphView.java:301)
                                                                       at com.jjoe64.graphview.GraphView.onDraw(GraphView.java:323)
                                                                       at android.view.View.draw(View.java:16187)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15184)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-15 14:56:21.232 13650-13650/nicktxd.graphtest I/Process: Sending signal. PID: 13650 SIG: 9

My code:

` 
public class MainActivity extends AppCompatActivity implements AdapterView.OnClickListener{

    Button btStart;
    Button btCancel;
    ToggleButton tbtScroll;
    GraphView graph;
    Viewport viewport;
    static DrawThread thread;
    boolean autoScroll = false;
    private static double graphLastXValue = 0;
    private static double graphMaxXValue = 40;
    LineGraphSeries<DataPoint> series;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        this.getWindow().setFlags(WindowManager.LayoutParams.
                FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_main);
        butInit();
    }
    void butInit(){
        btStart = (Button) findViewById(R.id.bConnect);
        btStart.setOnClickListener(this);
        btCancel = (Button) findViewById(R.id.bDisconnect);
        btCancel.setOnClickListener(this);
        tbtScroll = (ToggleButton) findViewById(R.id.tbScroll);
        tbtScroll.setOnClickListener(this);
    }
    @Override
    protected void onResume() {
        super.onResume();
        graph = (GraphView) findViewById(R.id.graph);
        viewport = graph.getViewport();
        viewport.setScalable(true);
        viewport.setScalableY(true);
        viewport.setScrollable(true);
        viewport.setScrollableY(true);
        viewport.setBackgroundColor(Color.WHITE);
        viewport.setBorderColor(Color.BLUE);
        viewport.setDrawBorder(true);
        viewport.setMinX(0);
        viewport.setMaxX(20);
        Paint paint = new Paint();
        paint.setStyle(Paint.Style.FILL);
        paint.setStrokeWidth(10);
        paint.setPathEffect(new DashPathEffect(new float[]{8, 5}, 0));
        series = new LineGraphSeries<>();
        series.setTitle("Graph");
        series.setBackgroundColor(Color.BLACK);
        series.setDrawDataPoints(true);
        series.setDataPointsRadius(10);
        series.setThickness(8);
        series.setCustomPaint(paint);
        graph.addSeries(series);
        
series.setOnDataPointTapListener(new OnDataPointTapListener() {
            @Override
            public void onTap(Series series, DataPointInterface dataPoint) {
                Toast.makeText(getApplicationContext(), "On Data Point clicked: "+dataPoint, Toast.LENGTH_SHORT).show();
            }
        });
    }
    
@Override
    public void onClick(View view) {
        if(view.getId()==R.id.bConnect) {
            thread = new DrawThread();
            thread.start();
        }
        if(view.getId()==R.id.tbScroll){
            if(tbtScroll.isChecked())
                autoScroll = true;
            else
                autoScroll = false;
        }
    }

    class DrawThread extends Thread {
        public DrawThread() {
        }
        public void run() {
            while (true) {
                try {
                    try {
                        sleep(500);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                    DataPoint point;
                    int temp = (int)((Math.random()*50+1));
                    point = new DataPoint(graphLastXValue, temp);
                    series.appendData(point, autoScroll, 40);
                    graphLastXValue++;
                }
                catch (Exception e) {
                    break;
                }
            }
        }
    }
}  `

**Comment by appsthatmatter** [comment]
could be fixed in the meantime
